name: nodemcu_controller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http:

  flutter_highlight:
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/play_store.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
